### ISSUE TITLE
angstrom-lwt-unix has ocaml < 4.06 constraint in opam for some reason

### ISSUE THREAD

**Issue by Freyr666** [inhabitedtype/angstrom#108]
It seems that it should work fine with --safe-string, but it is unavailable for 4.06

**Comment by hannesm** [comment]
well, the latest release doesn't compile with 4.06.0 -- see the logs at http://obi.ocamllabs.io/logs/2a78da8610334bf991cb988508040e85.txt (and the opam-repository PR at https://github.com/ocaml/opam-repository/pull/10750).  What would indeed be highly appreciated is an angstrom release since the current HEAD works fine with 4.06.0 AFAICT.

**Comment by seliopou** [comment]
Just opened a PR to fix it. I need to get that merged and take a look at @dinosaure's outstanding issue before cutting another release. I might also just cherry-pick these patches onto the release branch (which is still at the 0.7.0 tag) and do a 0.7.1 release.

**Comment by cfcs** [comment]
What is the status of this?

**Comment by seliopou** [comment]
This is fixed in master, and will make it into the next OPAM release.
