### ISSUE TITLE
What are the `string list` and `string` in `Fail`?

### ISSUE THREAD

**Issue by neojski** [inhabitedtype/angstrom#148]
```ocaml
| Fail of unconsumed * string list * string (** The parser failed. *)
```

From the ml I can see it's `marks` and `msg`. I can imagine what `msg` is but what are marks?

**Comment by seliopou** [comment]
The list contains the active marks at the time of the failure. Marks are introduced by the `<?>` combinator, whose only purpose is to be reported in the case of a failure. For example, if you had a `token` parser that accepted a sequence of alphanumeric characters (no spaces), and you wanted to write a parser that would quote a token, and required it to end with a semicolon, you could write:

```ocaml
let token_with_semicolon = token <* char ';'
let quoted_token = (char '"' *> (token_with_semicolon <?> "token_with_semicolon") <* char '"') <?> "quoted_token"
```

Then if you tried to run

```ocaml
parse_string quoted_token "\"abc\""
```

it would result in the error:

```
Result.Error "quoted_token > token_with_semicolon > ;: satisfy"
```

because it's missing the semicolon within the parser marked by `"token_with_semicolon"`, which is itself in a parser marked by `"token"`.

But if you tried to run

```ocaml
parse_string quoted_token "abc\""
```

it would result in the error:

```
Result.Error "quoted_token > \": satisfy"
```

because it's missing the leading quote, which is just in the parser marked by `"token"`.

**Comment by neojski** [comment]
Thank you, that's very helpful. In the above error messages isn't the `: satisfy` part a bit confusing though? You have to know that it's read ";" ": satisfy" and not ";: satisfy". Anyway, that's a very minor point.

Are the marks something that should be used for reporting line numbers in the errors? I wrote some very basic [subset of markdown parser](https://github.com/neojski/random/blob/5c470e7744c420796248d5597dae415e8195f85c/simple-markdown-parser/src/main.ml) to parse feature descriptions in order to produce rollout emails and line numbers would be helpful in error messages.

**Comment by seliopou** [comment]
In the latest master, the error message for the `char` parser is no longer `"satisfy"` but instead `"char <the char you're trying to parse>"`.

The issue of line numbers have come up in the past, I believe on the OCaml list, and as I stated then adding line numbers would adversely affect performance, so that won't be recorded and reported in the failure case for the parser. In the `Unbuffered` module, the first `int` provided in the `Fail` case is the byte position where the failure occurred, you could use to determine a line number after the fact. That's not exposed in the `Buffered` module, so maybe there's room for improvement there. I'd be happy to merge that change.

Thanks for your question!
