### ISSUE TITLE
Restricting parsers

### ISSUE THREAD

**Issue by andreypopp** [inhabitedtype/angstrom#151]
I have a question regarding how to compose parsers.

Suppose I have a reusable parser `url` which is defined as:
```
let url =
  Angstrom.(take_while (fun _ -> true) >>= makeUrl)
```

Now if I want to parse two urls delimited by `|` symbol I write:
```
Angstrom.(
  lift (fun x y -> x, y)
  <$> url <* char '|'
  <*> url
)
```
which is clearly doesn't work as first url will try to consume as much as possible.

I wonder if it's possible to constraint `url` as usage site, something like:
```
Angstrom.(
  lift (fun x y -> x, y)
  <$> parse_while (fun c -> c <> '|') url <* char '|'
  <*> url
)
```

Thank you!

**Comment by seliopou** [comment]
`take_while` will not backtrack through individual characters that it has consumed, as the `choice` operator is not used anywhere in its implementation. In order to get a parser to compose in the way you'd like it you, you'll have to restrict the characters that your parser will accept. Right now, it will just consume your entire input and try to turn that into a URI, which will pretty much always fail.

One way to accomplish your immediate goal is to just not allow URI's to contain `|` characters:

```ocaml
let url = Angstrom.(take_while (fun c -> c <> '|') >>= makeUrl)
```

A better solution would be to check out the RFC that defines the grammar and acceptable characters that a URI may contain, and use that as a guide for determining the characters to accept. I don't know for sure, but I'd wager that `|` is not a character that can appear in a URI.

An even better solution would be to write a URI parser in angstrom that takes the grammar into account. It's a lot more work but you won't be able to get more precise and composable than than.
