### ISSUE TITLE
consumed is unsafe

### ISSUE THREAD

**Issue by thedufer** [inhabitedtype/angstrom#198]
Consumed can cause a parser to raise if there is a commit in the parser passed to it.  For example, the parser

    consumed (char 'a' <* commit <* char 'b')

will raise if passed the inputs `"a"` and `"b"` in sequence.

**Comment by thedufer** [comment]
@dpatti It looks like you wrote this implementation.  I don't have a great idea of how to fix this.

**Comment by dpatti** [comment]
To add more context, the test

```ocaml
      check_s ~msg:"with more input at commit points"
        (consumed (char 'a' *> commit *> char 'b' *> commit *> char 'c'))
        ["a"; "b"; "c"] "abc";
```

produces the exception

```
[invalid] Bigstringaf.substring invalid range: { buffer_len: 1, off: -2, len: 3 }
```

I also don't have a good idea of how to fix this. Unless I'm mistaken, you basically only have access to the first and final `input`, and some arbitrary number of buffers might have existed in between.

**Comment by dpatti** [comment]
@seliopou and I talked today. If we can find a better solution that just makes it work, that's great. But since I'm suspecting that would be really invasive, the backup plan was to make a quick change such that `consume` fails if `commit` is used at all in the parser provided to it. It's not the most elegant solution, but I think the use case of `consume` leads to non-conventional combinators that throw away input anyway, so it doesn't seem like the worst trade-off.

@thedufer Can you elaborate on how you ended up with a commit inside your consume so I can make sure I'm not over-simplifying?

**Comment by thedufer** [comment]
Just failing seems better than raising, at least.  I don't have any better ideas.

I ended up with a commit inside my consume because I had to review this change and it looked like if I did so it would crash.  I have no real use-case here.
