### ISSUE TITLE
is defining a paser by `let rec` good

### ISSUE THREAD

**Issue by arbipher** [inhabitedtype/angstrom#202]
I am a bit confused and please allow me to ask it here if it's a naive question.

The API contains `val fix : ('a t -> 'a t) -> 'a t` and i'm thinking it's the only or suggested way to write a recursive parser, as the json example did. However, in the example of the [main page](https://github.com/inhabitedtype/angstrom)

```
let chainl1 elem op =
  let rec foldl acc =
    (op <*> return acc <*> elem) >>= foldl <|> return acc in
  elem >>= foldl
```
`fold1 : int -> int t` is recursive.  we can define a recursive parser using `let rec` rather than `fix`.

Is there any fundamental difference between these two approaches? Do they only differ for convenience?

**Comment by thedufer** [comment]
Note that `foldl` is not a parser (it's a function) and thus can't be constructed with `fix`.

You could write a recursive parser without `fix`, but it would be quite unwieldy.  You can't do it in the most obvious way:

    let rec foo = char 'x' *> foo <|> return ()

That's a compile error (not a valid use of `let rec`).  You could instead make it a thunk:

    let rec foo () = char 'x' *> foo () <|> return ()

But that immediately stack overflows.  Instead what you have to do is make it a thunk, but ensure the recursion only happens at parse time:

    let rec foo = char 'x' *> (return () >>= foo) <|> return ()

This is kind of an absurd construction.  Instead, just use fix:

    let foo = fix (fun foo -> char 'x' *> foo <|> return ())

**Comment by arbipher** [comment]
Thanks!

With the help of your answer, I realize my initial question is like asking why I cannot `let rec x = x` (while the answer is like `let rec x () = x ()` and `let rec x () = lazify (x ())`.

**Comment by arbipher** [comment]
Can I also ask how to define mutually recursive parsers? It seems the truck way works.

**Comment by thedufer** [comment]
I think the easiest way to make mutually-recursive parsers `a` and `b` is:

    let a b = fix (fun a -> (* definition of `a` in terms of `a` and `b` *))
    
    let b =
      fix (fun b ->
          let a = a b in
          (* definition of b in terms of `a` and `b` *))
    
    let a = a b

The first usage if `fix` is unnecessary if you don't need `a` to refer to itself.

**Comment by thedufer** [comment]
> `fix_lazy ` has an internal count `max_steps`. what is the purpose of this state?

Sorry, missed this question originally.  Note that `fix` only calls down to `fix_lazy` in cases where the backend is neither Bytecode nor Native.  In effect, this is JavaScript-only code.

`js_of_ocaml` does some tail-call optimization, but not as much as the main compiler.  What that code does is switches to a more TCO-friendly pattern every 20 recursive steps, to give `js_of_ocaml`'d code a chance to clear the stack.  Without the special-case for JavaScript-compiled code, parsing large documents would often stack-overflow in that environment.  It's only done every 20 steps because it is more expensive, so we do the fast thing 95% of the time.

**Comment by arbipher** [comment]
Thanks for the explanation on `fix_lazy`.
