### ISSUE TITLE
Add a version of count returning string

### ISSUE THREAD

**Issue by martindemello** [inhabitedtype/angstrom#53]
Can't think of a good name or I'd have submitted a PR :) But basically `count n pred >>| string_of_list` seems useful enough to be a standard part of the library, for parsing things like fixed-length hex strings.

**Comment by seliopou** [comment]
If I understand correctly, `count` would have the type:

```ocaml
val count : int -> (char -> bool) -> string
```

where both the first and second argument define stopping conditions, one based on length, and the other based on whether the predicate has yet to return false. So it's a length-bounded `take_while`. That seems like a really specific requirement, especially if it's just for grabbing a fixed-length string to continue parsing. The subsequent parsing would itself do the checks that the predicate would do, which means that each byte would be inspected twice rather than once. (Counting the number of times you look at a character is a good cost model for parser performance.) Compare this parser:

```ocaml
count n is_hex >>| parse_hex
```

with this parser:

```ocaml
take n >>| parse_hex
```

They should accept the same strings and return identical results, but one would expect the latter to be faster than the former (over large inputs). And of course, `parse_hex` need not return an int. It can just return the same string, but verify all the characters are hex characters:

```ocaml
let parse_hex s =
  if not (String.for_all_char s hex_pred)
  then fail "parse_hex"
  else return s
```

All that being said, this issue is very close to another that I've thought about, and that's including a constructor for stateful parsers, something along the lines of attoparsec's `scan` function:

```ocaml
val scan : 'a -> ('a -> char -> 'a option) -> 'a * string
```

Using this, you could implement your parser like this:

```ocaml
let count n p =
  snd (scan 0 (fun acc c -> if p c && acc < n then Some (acc + 1) else None))
```

Would something like that suit your needs?

**Comment by martindemello** [comment]
I was thinking of the case where we only needed to run parse_hex to validate the string was a hex number, so that rather than doing `take n >>| parse_hex` we can do `count n is_hex`.

As for being too specific, I think a common use case for this would be parsing binary structures with fixed length strings, where we can validate as we parse and fail early. See the [ext3 superblock example from bitstring](https://github.com/mor1/ocaml-bitstring/blob/master/examples/ext3_superblock.ml), e.g. - the uuids are fixed length strings with no further processing needed, but it would be handy to check that they only contain valid characters as we parse them. I see it not so much as a length bounded `take_while` but as a version of `count` that automatically does the final `list->string` step for you (indeed, I have it defined in my code as `count >>| CCString.of_list`, though that's probably not the most efficient way).

**Comment by seliopou** [comment]
The validation step you described is what `parse_hex` above implements. It just maps the `hex_pred` function over every character of the string and fails if any character is not a hex character. Otherwise, it returns the now-validated string unchanged.

In general, `count n p` seems to be equivalent to equivalent to:

```ocaml
take n >>= fun s -> if p s then return s else fail "invalid"
```

The nice thing about implementing it like this is that in the case of a failure that propagates all the way back to the user, the failure will pinpoint whether it came from a bad input length (`"take"`) or bad content (`"invalid"`).

But I'm still not clear on one thing, what's the failure condition that both `n` and `p` describe? If `p` returns false before `n` characters are consumed, what happens? If that would cause`count n p` to succeed, returning a string of length less than `n`, that seems like really confusing semantics and would be something better left to the user to hand-roll. If on the other hand that would cause `count n p` to fail, that would be consistent with my previous understanding, in which case I would want to keep the two stages separate.

**Comment by martindemello** [comment]
Right, I meant for `count n p` to fail if there are not exactly `n` characters all of which satisfy `p`. You're right about it losing the opportunity to present to different failure messages, though; I hadn't thought about that.

**Comment by seliopou** [comment]
Thanks for the suggestion&mdash;and the smooth and productive back-and-forth&mdash;but unfortunately I'm going to hold back on including this in the library for now and for the foreseeable future. If you have any other questions or suggestions, I would encourage you to share and discuss them on this issue tracker.
