### ISSUE TITLE
How to develop with angstrom?

### ISSUE THREAD

**Issue by michipili** [inhabitedtype/angstrom#69]
This is a question about the development lifecycle of parser written with angstrom.

What are the elements of practical approach to parser development? In my experiments I found out, it is really easy to lead the parser in an endless loop. The lack of location in error reporting also *seems* like an obstacle in parser development. I would therefore appreciate a general guidance about how to write parsers with angstrom, I have tried to write concrete, specific questions:

- When writing a complex parser broken down in many simpler language elements, is it common practice to unit-test all these language elements?

- How to gain more insight about a parsing error than what the `Fail` value reveals? The question is probably about how to use the `<?>` operator properly?

- Is there an easy rule of thumb to avoid infinite loops?

These questions are probably very basic, maybe they are already covered in some popular article, in which case a reference would probably enough.

Thank you for your good work on angstrom!

**Comment by seliopou** [comment]
These are all good question, but they're also big ones! I'll try to answer them one at a time in separate responses.

First, about infinite loops. The simplest way to write an infinite loop that I can think of is:

```ocaml
many (return ())
```

To understand why this is an infinite loop, let's first look at `many`. Conceptually, what`many p` does is run `p` repeatedly _until it fails_. Once `p` fails, `many` collects the results of all of `p`'s previously successful runs, and returns them in a list. So `many (fail "nothing")`, run on _any_ input will simply return the empty list, as `fail` always... well, fails. On the other hand, if you run `many (char 'a')` on the input `"aabb"`, you'll get a list of length 2 that contains `'a'`'s.

So what about `many (return ())`? In this case `return ()` _always succeeds_. Not only does it always succeed, it also necessarily _never consumes input_. What that means is that `many` will attempt to run `return ()` once, which will succeed while not advancing the input, and then it'll try to run it again, and again, and again, again. And you have an infinite loop.

As far as I can tell, all infinite loops that you can write with parser combinators have this form: you have a combinator that uses failure of one of its arguments to indicate termination, but the argument  never fails. There's probably a bunch of ways that this can be disguised, but I sadly don't have a taxonomy ready and available.

The one rule of thumb that I can offer is that you should make sure that your parser is at every stage consuming input. If your using parsers that potentially might not consume input, .e.g, `take_while`, `skip_while`, `peek`, you should be very critical of the context in which you're using them. `skip_while`, for example, can be very useful to skipping over whitespace. That's a legitimate use. However, the very next thing your parser should do is check for something that is _not_ whitespace.

It might be tempting, for example, to write a "tokenizer" for a language along these lines:

```ocaml
let token = choice [
  skip_while is_whitespace;
  some_token;
  another_token;
  ...
]

let tokens = many tokens
```

But, you fall into the same trap here. `token` always succeeds without consuming input because `skip_while` will always succeed and does not _have to_ consume input. That means that `tokens` will never terminate either.

A better way to write this that avoids this trap is:

```ocaml
let token' = skip_while is_whitespace *>
  choice [
    some_token;
    another_token;
    ...
  ]

let tokens' = many token'
```

The use of `skip_while` here is ok, assuming that the other token parsers in the `choice` can fail. Since that ensures that the choice can fail, esuring that `tokens'`.

But, if it's absolutely necessary to generate a "whitespace token", you can simply switch to using `skip_while1` instead:

```ocaml
let token'' = choice [
  skip_while1 is_whitespace;
  some_token;
  another_token;
  ...
]

let tokens'' = many tokens
```

I'm running out of steam, but hopefully you get the point! More tomorrow.

**Comment by michipili** [comment]
Thank you for your valuable answer! Does these parser that “does not need to consume input” have a well-known name? (If not, what about a “frugal” parser?)  It looks like the property of being a frugal parser can, at leas in certain cases, be deduced from the iterators, like e.g.: if any candidate to a `choice` is frugal, then the resulting parser is also `frugal`. 

Do you think this property is well-behaved enough so that it can be nicely documented?

**Comment by michipili** [comment]
Let's close this issue, since it is very general and already contains valuable bits of information. Thanks!
