### ISSUE TITLE
"Lazy" version of many_till?

### ISSUE THREAD

**Issue by mattjbray** [inhabitedtype/angstrom#72]
Thanks for this awesome library.

I keep getting bitten by the greedy nature of `many_till` (to use Regex parlance).

I've been using my own `many_till_lazy`, which is the same as `many_till` but with the order of the parsers switched:

```ocaml
let many_till_lazy p t =
  fix (fun m ->
    (t *> return []) <|> (lift2 cons p m))
```

For example:

```ocaml
let my_string =
  String.concat "\n"
    [ "- Some stuff;"
    ; "- Some more stuff;"
    ; ""
    ]

let parser : string list t =
  let line_parser =
    string "- " *> many_till any_char (char ';' *> end_of_line)
    >>| Stringext.of_list
  in
  many line_parser
```

Using `Angstrom.many_till` in `line_parser`, running `parser` on `my_string` will result in a list with a single element:
```ocaml
["Some stuff;\n- Some more stuff"]
```

Whereas with `many_till_lazy`, I get the expected:
```ocaml
["Some stuff"; "Some more stuff"]
```

I guess my questions are:

* Is there a better way to get this functionality, without defining a custom `many_till_lazy`?
* Is the greedy behaviour of `many_till` by design?
* Does flipping the order of the parsers as I have done in `many_till_lazy` affect parser performance?

**Comment by seliopou** [comment]
Thanks for using the library, and asking your question!

Right off the bat, I think that your implementation of `many_till_lazy` is much more useful than the one that's currently in `master`. There's no need to introduce a new name, just replacing the implementation of `many_till` with yours would be sufficient. If you'd like to send a pull request, I'll merge it.

For combinators like `many`, and `many_till`, or any combinators that are implemented by using backtracking (e.g., [`<|>`](https://github.com/inhabitedtype/angstrom/blob/master/lib/angstrom.mli#L278-L280)), I'm not particular concerned with how they perform because they are inherently inefficient! As much as possible, you should aim to have your parsers inspect each character of your input _only once_. When you use backtracking, you're never quite sure if that's going to be the case, and even if it is, you end up allocating a bunch of failure continuations along the way. The new implementation of `many_till` will definitely do a lot more failing in order to get the result you desire, but there are other ways that the library allows you the parse the sorts of input you're looking to parse, so I consider this to be OK.

If you're interested, here's how I would rewrite your parser so that it uses less backtracking, and then no backtracking at all. These parsers also don't allocate an intermediate list of character that are then just used to construct a string. Instead of doing that, you can do away with the use of `many_till` and just use [`take_while`](https://github.com/inhabitedtype/angstrom/blob/master/lib/angstrom.mli#L111-L113) to return a string directly:

```ocaml
let is_not_semi c = c <> ';'
let line : string t =
  string "- " *> take_while (is_not_semi';') <* char ';' <* end_of_line

let parser : string list t =
  many line
```

But this still uses `many` and therefore still uses backtracking, which is allocating closures that you don't need and may _possibly_ be inspecting more characters than necessary to detect failure, depending on the input. You can avoid both of these issues by using `fix` to write your own non-backtracking loop:

```ocaml
let cons x xs = x::xs

let parser : string list t =
  fix (fun p ->
    peek_char >>= function
    | Some '-' -> lift2 cons line p
    | _        -> return [])
```

Hope this helps. I'll leave this open until the change to `many_till` make it in. Let me know if you intend to send a pull request.

Related to #69.

**Comment by mattjbray** [comment]
Thank you, that's a really helpful answer. I'll send a pull request.
