### ISSUE TITLE
Lookbehind support?

### ISSUE THREAD

**Issue by igstan** [inhabitedtype/angstrom#78]
Hi! Does Angstrom support a way to look at (some of) the previous character(s)? For example, match any character that's not preceded by `#`. If not, what would a possible solution/workaround look like? Just to make sure, I don't want a full solution to this problem, just some hints as to what API calls I might use.

Thanks!

**Comment by seliopou** [comment]
You can accomplish this by using the `>>=` operator to parse the section of input you're interested in and close over it in the continuation of the parse:

```ocaml
take_while (fun c -> not (Char.equal c '#')) >>= fun pre_hash->
any_char (* consume hash *)
*> (* the rest of your parser can refer to `pre_hash` to access the input prior to the '#' character *)
```

Does this answer your question?

**Comment by igstan** [comment]
I don't think it does. What I want is akin to the `peek_char` combinator, but in reverse. The preceding character has already been consumed by a parser I don't have control over. Something like this, but where the actual `'#'` char has already been consumed by someone else before me.

```ocaml
char '#' *>
prev_char >>= function
| '#' -> return "yes"
| _ -> fail "# prefix missing"
```

The above would match the single-character string `"#"`. Does this make sense?

**Comment by seliopou** [comment]
In this particular case, `prev_char` is not necessary because `char` returns the character it consumes:
```ocaml
char '#' >>= function
| '#' -> return "yes"
| _   -> fail '# prefix missing"
```
In other words, if you use bind, it will allow you to hold onto the result of a previous parse for inspection at a later time, as I described above.

But also, with the exception of the different error message, this is just equivalent to:

```ocaml
char '#' *> return "yes"
```
And to recover the error message behavior, you could also do this:

```ocaml
(char '#' <|> fail "# prefix missing") *> return "yes"
```
... but I'd avoid using choice for performance reasons.

**Comment by seliopou** [comment]
Closing this as I believe I've addressed your issue, but feel free to continue discussion.
